// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type BusinessListReq struct {
	LastId             int64 `json:"lastId"`
	PageSize           int64 `json:"pageSize"`
	HomestayBusinessId int64 `json:"homestayBusinessId"`
}

type BusinessListResp struct {
	List []Homestay `json:"list"`
}

type GuessListReq struct {
}

type GuessListResp struct {
	List []Homestay `json:"list"`
}

type HomestayDetailReq struct {
	Id int64 `json:"id"`
}

type HomestayDetailResp struct {
	Homestay Homestay `json:"homestay"`
}

type HomestayListReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
}

type HomestayListResp struct {
	List []Homestay `json:"list"`
}
