// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CommentListReq struct {
	LastId   int64 `json:"lastId"`
	PageSize int64 `json:"pageSize"`
}

type CommentListResp struct {
	List []HomestayComment `json:"list"`
}
