// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type UserHomestayOrderListView struct {
	Sn              string  `json:"sn"`              //单号
	Title           string  `json:"title"`           //标题
	SubTitle        string  `json:"subTitle"`        //副标题
	HomestayId      int64   `json:"homestayId"`      //民宿id
	Cover           string  `json:"cover"`           //封面
	OrderTotalPrice float64 `json:"orderTotalPrice"` //订单总价格
	CreateTime      int64   `json:"createTime"`      //下单时间
	TradeState      int64   `json:"tradeState"`      //-1: 已取消 0:待支付 1:未使用 2:已使用  3:已退款 4:已过期
	LiveStartDate   int64   `json:"liveStartDate"`   //入驻开始日期
	LiveEndDate     int64   `json:"liveEndDate"`     //入驻结束日期
	TradeCode       string  `json:"tradeCode"`       //交易码
}
